services:
  its-service:
    build: 
      context: .
      args:
        - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/its_dev?useSSL=false&allowPublicKeyRetrieval=true
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=root
        - USERNAME=armfahim
      network: host
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/its_dev?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database
    # networks:
    #   - mysql-network

  database:
    image: mysql:8.0.27
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=its_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    # networks:
    #   - mysql-network

# networks:
#   mysql-network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16
#           gateway: 172.28.5.254

